Repository Perl/perl5, pull requests merged in 2020-07, with the labels that each got.

#17915 Make perl compile under minix again
  perl.h
Labels: affects-5.32, backport-5.32, distro-minix

#17933 groups.t: Correct one syntax error which was warning
  t/op/groups.t
Labels: discovered-thru-p7-research

#17944 Dumpvalue.t: Tighten scope of package variables.
  dist/Dumpvalue/t/Dumpvalue.t
Labels: discovered-thru-p7-research

#17706 HTTP::Tiny needs two modules for https support
  Porting/sync-with-cpan
Labels: Infrastructure, affects-5.34

#17657 win32.c: rework the waitpid(-1, WNOHANG) fix
  win32/win32.c
Labels: do not merge

#17649 intrpvar.h -reorder PERLVARS to close x86-64 alignment holes
  intrpvar.h
Labels: optimization

#17977 Fix format issue in t/op/taint.t and add strict/warnings
  t/op/taint.t
Labels: discovered-thru-p7-research

#17930 Fix 404 and text in New Unicode properties section
  pod/perl5320delta.pod
Labels: backport-5.30, backport-5.32, documentation

#17835 pp.c/pp_hot.c - add fast path for comparing 2x SvNOKs
  pp.c
  pp_hot.c
Labels: Ready-to-merge, Severity Low, optimization, performance, target-5.34

#17624 Remove obsolete FCRYPT ifdefs and associated PL_cryptseen
  embedvar.h
  intrpvar.h
  makedef.pl
  perl.h
  pp.c
  sv.c
  toke.c
Labels: Ready-to-merge, needs-work, target-5.34

#17698 perl5db: allow the recorded history item length to be configured
  lib/perl5db.pl
Labels: type-debugger

#17552 Note range op behavior change in docs
  pod/perlop.pod
Labels: awaiting review, documentation

#17912 Fix Math-Complex issue in test suite
  cpan/Math-Complex/lib/Math/Complex.pm
  cpan/Math-Complex/t/Complex.t
  cpan/Math-Complex/t/Trig.t
  cpan/Math-Complex/t/underbar.t
  t/porting/customized.dat
Labels: awaiting review

#17936 Document warning 'readline() on unopened filehandle %s'
  pod/perldiag.pod
Labels: awaiting review, discovered-thru-p7-research, documentation
