Repository Perl/perl5, pull requests merged in 2020-10, with the labels that each got.

#18187 Update version to CPAN version 0.9928
  cpan/version/lib/version.pm
  cpan/version/lib/version.pod
  cpan/version/lib/version/regex.pm
  cpan/version/t/01base.t
  cpan/version/t/02derived.t
  cpan/version/t/03require.t
  cpan/version/t/04strict_lax.t
  cpan/version/t/05sigdie.t
  cpan/version/t/06noop.t
  cpan/version/t/07locale.t
  cpan/version/t/08_corelist.t
  cpan/version/t/09_list_util.t
  cpan/version/t/10_lyon.t
  cpan/version/t/coretests.pm
  t/porting/customized.dat
  vutil.c
  vutil.h
  vxs.inc
Labels: cpan-dual-life

#18072 Perl_av_extend_guts: initialize elements via Zero() rather than while loop(s)
  av.c
Labels: awaiting review

#18199 Make FindBin strict and warnings compliant
  dist/FindBin/lib/FindBin.pm
  dist/FindBin/t/FindBin.t
Labels: cpan-dual-life, strict

#18211 Update Pod::Checker to CPAN version 1.74
  MANIFEST
  Porting/Maintainers.pl
  cpan/Pod-Checker/lib/Pod/Checker.pm
  cpan/Pod-Checker/scripts/podchecker.PL
  cpan/Pod-Checker/t/pod/poderrs.t
  cpan/Pod-Checker/t/pod/poderrs.xr
  cpan/Pod-Checker/t/pod/podname.t
  cpan/Pod-Checker/t/pod/testpchk.pl
Labels: cpan-dual-life

#18210 Update Digest::MD5 to CPAN version 2.57
  MANIFEST
  Porting/Maintainers.pl
  cpan/Digest-MD5/MD5.pm
  cpan/Digest-MD5/MD5.xs
  cpan/Digest-MD5/Makefile.PL
  cpan/Digest-MD5/hints/MacOS.pl
  cpan/Digest-MD5/hints/irix_6.pl
  cpan/Digest-MD5/t/align.t
  cpan/Digest-MD5/t/badfile.t
  cpan/Digest-MD5/t/bits.t
  cpan/Digest-MD5/t/clone.t
  cpan/Digest-MD5/t/files.t
  cpan/Digest-MD5/t/md5-aaa.t
  cpan/Digest-MD5/t/threads.t
  cpan/Digest-MD5/t/utf8.t
  cpan/Digest-MD5/t/warns.t
  t/porting/customized.dat
Labels: cpan-dual-life

#18217 perlutil updates and cleanup
  pod/perlutil.pod
  t/porting/known_pod_issues.dat
Labels: documentation, type-utilities

#18218 Add crosslinks between perl5db.pl and perldebug-related docs
  lib/perl5db.pl
  pod/perldebguts.pod
  pod/perldebtut.pod
  pod/perldebug.pod
Labels: documentation

#18158 pp_split: reify using NULL rather than PL_sv_undef (gh#18077)
  pp.c
Labels: Ready-to-merge

#18235 Fix enough code to get make test_prep working with -Dusedefaultstrict
  dist/if/if.pm
  lib/Getopt/Std.pm
  lib/Getopt/Std.t
  lib/Symbol.pm
  lib/Symbol.t
  lib/bytes.pm
  lib/bytes.t
  lib/locale.pm
  lib/locale.t
  lib/overload.pm
  lib/subs.pm
  lib/utf8.pm
Labels: strict

#18236 Fix t/test.pl and t/TEST to be strict compliant.
  t/TEST
  t/test.pl
Labels: strict

#18150 t/opbasic/arith.t - deliberately exercise dleft/dright paths in pp_modulo
  t/opbasic/arith.t
Labels: awaiting review
