Repository Perl/perl5, pull requests merged in 2020-12, with the labels that each got.

#18403 t/lib/croak/toke: Correct test label
  t/lib/croak/toke
Labels: discovered-thru-p7-research

#18165 GH #18163: Stricter, cleaned up test example:
  dist/ExtUtils-ParseXS/lib/perlxstut.pod
Labels: documentation

#18390 skip trying to constant fold an incomplete op tree
  op.c
  t/op/cmpchain.t
Labels: backport-5.32

#18428 Porting/pod_rules.pl: no '--test' command-line switch
  Porting/pod_rules.pl
Labels: Infrastructure, documentation

#18429 Better documentation for two Porting/*.pl programs
  Porting/manifest_lib.pl
  Porting/pod_lib.pl
Labels: Infrastructure, documentation

#18427 pod/buildtoc: documentation in POD format
  pod/buildtoc
Labels: Infrastructure, documentation
