Repository Perl/perl5, pull requests merged in 2020-06, with the labels that each got.

#17834 perlhacktips.pod - update ASan section
  pod/perlhacktips.pod
Labels: Severity Low, documentation

#17788 Sync Configure with metaconfig
  Configure
Labels: affects-5.30, affects-5.32, backport-5.30

#17876 Cleanup of community stuff
  pod/perlcommunity.pod
Labels: documentation
