Repository Perl/perl5, pull requests merged in 2020-01, with the labels that each got.

#12 IO::Socket Documentation
  dist/IO/lib/IO/Socket.pm
Labels: DualLife, documentation, hasPatch

#17393 Change various search.cpan.org references to metacpan.org and www.cpan.org
  Porting/release_managers_guide.pod
  README.win32
  pod/perlhack.pod
  pod/perlmodinstall.pod
  pod/perlmodlib.PL
  pod/perlootut.pod
  pod/perlthrtut.pod
  t/porting/podcheck.t
  utils/h2xs.PL
  win32/makefile.mk
Labels: documentation

#17504 Correct misleading entries in SYNOPSIS
  MANIFEST
  dist/Tie-File/lib/Tie/File.pm
  dist/Tie-File/t/43_synopsis.t
Labels: dist/Tie-File
