Repository Perl/perl5, pull requests merged in 2020-08, with the labels that each got.

#17756 XSUB.h: fix MARK and items variables inside BOOT XSUBs
  XSUB.h
Labels: awaiting review

#18013 perlfunc.pod - when sleep() is called with a negative int
  pod/perlfunc.pod
Labels: Ready-to-merge

#17808 add a default enabled feature "multidimensional"
  MANIFEST
  feature.h
  lib/feature.pm
  op.c
  pod/perldiag.pod
  regen/feature.pl
  t/lib/feature/multidimensional
  t/porting/known_pod_issues.dat
Labels: Feature

#18100 pp_akeys: use av_top_index rather than Perl_av_len
  pp.c
Labels: awaiting review
