Repository Perl/perl5, pull requests merged in 2020-11, with the labels that each got.

#18287 perldata - example of using DATA
  pod/perldata.pod
Labels: documentation

#18288 POSIX - add versions to POSIX features
  ext/POSIX/lib/POSIX.pod
Labels: documentation, type-Module

#18294 Fix unitialized warnings in S_pmtrans
  op.c
Labels: build-time-warnings

#18360 perlsub - indicate version requirement for "delete local"
  pod/perlsub.pod
Labels: documentation

#18011 Add mutex locking for many-reader/1-writer
  perl.h
  thread.h
Labels: awaiting review

#18361 perlvar - clarify that paragraph mode also discards a single leading newline
  pod/perlvar.pod
Labels: documentation

#18342 add extra language in the quotemeta() docs for embedded \ and $
  pod/perlfunc.pod
Labels: documentation, type-parsing

#17500 'use warnings' with exceptions
  lib/warnings.pm
  regen/warnings.pl
  t/lib/warnings/2use
Labels: Feature Request, awaiting review
