Repository Perl/perl5, pull requests merged in 2021-05, with the labels that each got.

#18765 Fix perlop.pod about isa operator's precedence
  pod/perlop.pod
Labels: documentation

#18767 small touch-ups to the 5.34.0 perldelta
  pod/perldelta.pod
Labels: documentation, target-5.34

#18152 perldelta.pod: tweak -Dusedefaultstrict text
  pod/perldelta.pod
Labels: Severity Low, do not merge, documentation

#18782 set -fwrapv on by default unconditionally
  win32/GNUmakefile
Labels: affects-5.34

#18784 perldelta: unify styles
  pod/perldelta.pod
Labels: hasConflicts

#18802 perlcommunity - freenode chat is moving to libera
  pod/perlcommunity.pod
Labels: documentation

#18795 File::stat - Fix typo in synopsis
  lib/File/stat.pm
Labels: documentation

#18762 perlfunc - mention that delete can only be used on key-value slices since 5.28
  pod/perlfunc.pod
Labels: documentation

#18716 Moved 2 vars in perlvar to deprecated section
  pod/perlvar.pod
Labels: documentation

#18727 Do not cache utf8 offsets for non-canonical lengths
  embed.fnc
  proto.h
  sv.c
  t/op/index.t
Labels: type-Unicode

#18731 Update version from CPAN to 0.9929
  Porting/Maintainers.pl
  cpan/version/lib/version.pm
  cpan/version/lib/version/regex.pm
  cpan/version/t/01base.t
  cpan/version/t/02derived.t
  cpan/version/t/03require.t
  cpan/version/t/05sigdie.t
  cpan/version/t/06noop.t
  cpan/version/t/07locale.t
  cpan/version/t/08_corelist.t
  cpan/version/t/09_list_util.t
  t/porting/customized.dat
  vutil.c
  vutil.h
Labels: awaiting review, cpan-dual-life

#18833 perlcommunity - add a webchat link for Libera.Chat #perl
  pod/perlcommunity.pod
Labels: documentation

#18803 Clarify descriptions of unicode_eval and evalbytes.
  lib/feature.pm
  pod/perlfunc.pod
  regen/feature.pl
Labels: documentation
