Repository Perl/perl5, pull requests merged in 2021-08, with the labels that each got.

#19024 perlfunc 'ref' and UNIVERSAL: document isa operator alternative
  lib/UNIVERSAL.pm
  pod/perlfunc.pod
Labels: documentation

#19050 Pod html refactoring 5 of 5
  ext/Pod-Html/lib/Pod/Html.pm
  ext/Pod-Html/lib/Pod/Html/Util.pm
  ext/Pod-Html/t/htmldir3.t
  ext/Pod-Html/t/lib/Testing.pm
Labels: ext/Pod-Html

#19027 Porting/core-cpan-diff: Remove '--binary'
  Porting/core-cpan-diff
Labels: distro-freebsd, Infrastructure

#19061 Exporter: Document non-inheriting as default mechanism
  dist/Exporter/lib/Exporter.pm
  dist/Exporter/lib/Exporter/Heavy.pm
Labels: documentation

#18746 op.h: define missing BASEOP comment block fields (op_sibparent, op_targ)
  op.h
Labels: awaiting review

#19087 Reword discussion of /d regexp modifier.
  pod/perlre.pod
Labels: documentation
