Repository Perl/perl5, pull requests merged in 2021-02, with the labels that each got.

#18526 pp_split: calculate flags just once and other minor tweaks
  pp.c
Labels: awaiting review

#18494 ExtUtils-CBuilder: Remove image-base generation on Win32/gcc
  AUTHORS
  dist/ExtUtils-CBuilder/Changes
  dist/ExtUtils-CBuilder/lib/ExtUtils/CBuilder.pm
  dist/ExtUtils-CBuilder/lib/ExtUtils/CBuilder/Base.pm
  dist/ExtUtils-CBuilder/lib/ExtUtils/CBuilder/Platform/Unix.pm
  dist/ExtUtils-CBuilder/lib/ExtUtils/CBuilder/Platform/VMS.pm
  dist/ExtUtils-CBuilder/lib/ExtUtils/CBuilder/Platform/Windows.pm
  dist/ExtUtils-CBuilder/lib/ExtUtils/CBuilder/Platform/Windows/BCC.pm
  dist/ExtUtils-CBuilder/lib/ExtUtils/CBuilder/Platform/Windows/GCC.pm
  dist/ExtUtils-CBuilder/lib/ExtUtils/CBuilder/Platform/Windows/MSVC.pm
  dist/ExtUtils-CBuilder/lib/ExtUtils/CBuilder/Platform/aix.pm
  dist/ExtUtils-CBuilder/lib/ExtUtils/CBuilder/Platform/android.pm
  dist/ExtUtils-CBuilder/lib/ExtUtils/CBuilder/Platform/cygwin.pm
  dist/ExtUtils-CBuilder/lib/ExtUtils/CBuilder/Platform/darwin.pm
  dist/ExtUtils-CBuilder/lib/ExtUtils/CBuilder/Platform/dec_osf.pm
  dist/ExtUtils-CBuilder/lib/ExtUtils/CBuilder/Platform/os2.pm
Labels: Win32, distro-mswin32

#18571 Smoke me/jkeenan/gh 18570 t op magic
  t/op/magic.t
Labels: distro-dragonfly, distro-freebsd
