Repository Perl/perl5, pull requests merged in 2021-07, with the labels that each got.

#18166 GH #18047: Initial phrasing for =head5 and =head6
  pod/perlpod.pod
  pod/perlpodspec.pod
Labels: documentation

#18948 Silence build-time warning coming from scope.h
  scope.h
Labels: build-time-warnings

#18964 Haiku BFS does not store atime and always return current time
  dist/Time-HiRes/HiRes.pm
  dist/Time-HiRes/t/stat.t
  lib/File/stat.pm
  lib/File/stat.t
Labels: distro-haiku
