Repository Perl/perl5, pull requests merged in 2022-04, with the labels that each got.

#19577 Accept \p{nv=-0}
  regcomp.c
  t/lib/croak/regcomp
  t/re/re_tests
Labels: hasConflicts

#19620 expand wildcards in t/harness and use it for test_porting and test_reonly make targets
  Makefile.SH
  t/harness
Labels: build tooling

#19627 Update IO.xs to conform to ppport.h 3.68 recommendations
  dist/IO/ChangeLog
  dist/IO/IO.pm
  dist/IO/IO.xs
Labels: cpan-dual-life, dist-IO

#19629 Update Storable.xs to conform to ppport.h 3.68 recommendations
  dist/Storable/Storable.pm
  dist/Storable/Storable.xs
Labels: cpan-dual-life, dist-Storable

#19630 Update Time-HiRes.xs to conform to ppport.h 3.68 recommendations
  dist/Time-HiRes/HiRes.pm
  dist/Time-HiRes/HiRes.xs
Labels: cpan-dual-life

#19647 Normalize: Use ppport.h
  dist/Unicode-Normalize/Normalize.pm
  dist/Unicode-Normalize/Normalize.xs
Labels: cpan-dual-life

#19660 perlapi: Document SvPVXtrue
  sv.h
Labels: documentation

#19674 update const sub docs for stuff that now croaks
  pod/perlsub.pod
Labels: documentation
