Repository Perl/perl5, pull requests merged in 2022-11, with the labels that each got.

#20475 buildtoc: Add error check
  pod/buildtoc
Labels: Infrastructure

#20439 allow porting/corelist.t to be run from root
  t/porting/corelist.t
Labels: Infrastructure

#20531 t/op/readline.t: skip error handling checks on solaris with PERLIO=stdio
  t/op/readline.t
Labels: distro-Solaris

#20561 pod2html: sort command-line switches
  ext/Pod-Html/bin/pod2html
Labels: ext/Pod-Html
