Repository Perl/perl5, pull requests merged in 2022-05, with the labels that each got.

#19677 Document CvDEPTH
  embed.fnc
  inline.h
Labels: documentation

#19658 perlop: Clarify parts of tr///
  pod/perlop.pod
Labels: documentation

#19698 perlapi: Mark PerlIO_context_layers internal
  embed.fnc
Labels: documentation

#19686 perlintern: Make hv_fill internal, HvFILL its API
  embed.fnc
  hv.c
  hv.h
Labels: documentation

#19691 Make t/op/magic.t pass on AlmaLinux 8’s kernel.
  t/op/magic.t
Labels: Release Blocker

#19725 Sync Compress-Raw-Zlib-2.104 into blead
  Porting/Maintainers.pl
  cpan/Compress-Raw-Zlib/Makefile.PL
  cpan/Compress-Raw-Zlib/lib/Compress/Raw/Zlib.pm
  cpan/Compress-Raw-Zlib/t/02zlib.t
  cpan/Compress-Raw-Zlib/zlib-src/zconf.h
  cpan/Compress-Raw-Zlib/zlib-src/zlib.h
Labels: Release Blocker

#19709 Win32: synch with CPAN version 0.59
  cpan/Win32/Win32.pm
  cpan/Win32/Win32.xs
  cpan/Win32/t/Names.t
Labels: Release Blocker

#19711 perlapi: Document repeatcpy
  embed.fnc
  util.c
Labels: documentation

#19715 perlapi: Document newGVgen(_flags)?
  embed.fnc
  gv.c
Labels: documentation

#19730 Sync Compress-Raw-Zlib-2.105 into blead
  Porting/Maintainers.pl
  cpan/Compress-Raw-Zlib/Makefile.PL
  cpan/Compress-Raw-Zlib/Zlib.xs
  cpan/Compress-Raw-Zlib/lib/Compress/Raw/Zlib.pm
  cpan/Compress-Raw-Zlib/t/01version.t
  cpan/Compress-Raw-Zlib/t/02zlib.t
Labels: Release Blocker

#19744 perlapi: Document re_compile
  embed.fnc
  regcomp.c
Labels: documentation

#19679 Revert "Add Configure question for taint support"
  Configure
  Cross/config.sh-arm-linux
  Cross/config.sh-arm-linux-n770
  Porting/config.sh
  configure.com
  metaconfig.h
  plan9/config_sh.sample
  pod/perlipc.pod
  pod/perllocale.pod
  pod/perlmodstyle.pod
  pod/perlrun.pod
  pod/perlsec.pod
  uconfig.h
  uconfig.sh
  uconfig64.sh
  win32/config.gc
  win32/config.vc
Labels: Release Blocker

#19739 perlapi: Clean up some AV documentation
  av.c
  av.h
  embed.fnc
Labels: documentation

#19752 perlapi: Document do_sprintf
  doop.c
  embed.fnc
Labels: documentation

#19751 perlapi: Document do_join
  doop.c
  embed.fnc
Labels: documentation

#19741 perlapi: Document sv_dup(_inc)?
  embed.fnc
  sv.c
Labels: documentation

#19636 regexec.c: Rmv obsolete recursion checks: GH #8369
  pod/perldiag.pod
  regexec.c
Labels: defer-next-dev

#19692 Fix a typo in a comment in Carp.pm
  dist/Carp/lib/Carp.pm
  dist/Carp/lib/Carp/Heavy.pm
Labels: defer-next-dev

#19600 Add B helpers to check if the Sv is a boolean
  MANIFEST
  ext/B/B.pm
  ext/B/B.xs
  ext/B/t/bool.t
Labels: ext/B, defer-next-dev

#19599 Extra B::PADNAME helpers: GEN and IsUndef
  ext/B/B.pm
  ext/B/B.xs
Labels: ext/B, defer-next-dev

#19665 Evaluate SvPVXtrue's argument just once
  embed.fnc
  embed.h
  inline.h
  proto.h
  sv.h
Labels: defer-next-dev

#19666 Evaluate arg in SvIV and kin just once
  embed.fnc
  embed.h
  inline.h
  proto.h
  sv.h
Labels: defer-next-dev

#19646 GH16319: avoid recursion parsing 'pack' template
  pod/perldiag.pod
  pp_pack.c
  t/op/pack.t
Labels: defer-next-dev
