Repository Perl/perl5, pull requests merged in 2022-12, with the labels that each got.

#20581 pod2html: Group '*' and 'no*' switches in documentation
  ext/Pod-Html/bin/pod2html
Labels: ext/Pod-Html, squash-before-merge

#20552 perlsub: normalize whitespace to use 4 space indents
  pod/perlsub.pod
Labels: documentation

#20116 threads.xs: Fix warning "implicit declaration of function '_setjmpex'" using MinGW-w64
  AUTHORS
  dist/threads/lib/threads.pm
  dist/threads/threads.xs
Labels: distro-mswin32, type-threads

#20603 Do not cast away constness
  AUTHORS
  hv_func.h
  hv_macro.h
  inline.h
  sbox32_hash.h
  zaphod32_hash.h
Labels: build-time-warnings

#20642 Revert "harness: handle directories serial/parallel mixture"
  t/harness
Labels: smoke, revert

#20643 Re-enable full blown parallel tests without using heuristics to detect special cases.
  t/harness
Labels: type-test-infra
