Repository Perl/perl5, pull requests merged in 2022-10, with the labels that each got.

#20387 locale.c: Fix Debug statement on netbsd
  locale.c
Labels: distro-netbsd

#20386 locale.c: Silence unused var warning on dragonfly
  locale.c
Labels: distro-freebsd

#20405 perlsub - replace uses of $a and $b in examples
  pod/perlsub.pod
Labels: documentation

#20403 locale.c: Don't compile get_displayable_string if unused
  embed.fnc
  embed.h
  locale.c
  proto.h
Labels: build-time-warnings

#20397 Better handling of builtin CV attributes
  embed.fnc
  embed.h
  perly.act
  perly.h
  perly.tab
  perly.y
  proto.h
  t/op/attrs.t
  toke.c
Labels: squash-before-merge

#20423 Fix fegetround on s390x with clang
  ext/POSIX/POSIX.xs
  ext/POSIX/lib/POSIX.pm
Labels: distro-os390
