Repository Perl/perl5, pull requests merged in 2022-03, with the labels that each got.

#19329 Add PerlIO_readlink backcompat defines to Cwd.xs
  dist/PathTools/Cwd.pm
  dist/PathTools/Cwd.xs
  dist/PathTools/lib/File/Spec.pm
  dist/PathTools/lib/File/Spec/AmigaOS.pm
  dist/PathTools/lib/File/Spec/Cygwin.pm
  dist/PathTools/lib/File/Spec/Epoc.pm
  dist/PathTools/lib/File/Spec/Functions.pm
  dist/PathTools/lib/File/Spec/Mac.pm
  dist/PathTools/lib/File/Spec/OS2.pm
  dist/PathTools/lib/File/Spec/Unix.pm
  dist/PathTools/lib/File/Spec/VMS.pm
  dist/PathTools/lib/File/Spec/Win32.pm
Labels: dist-PathTools

#19493 hv.c: ALWAYS perform in_collision check
  hv.c
Labels: Critical Change

#19216 Fixed possible syntax error in Configure's test program for Inf/NaN bytes
  Configure
Labels: type-configure

#19505 t/op/magic.t - Issue #19504 - fixup tests for utf8 $0
  t/op/magic.t
Labels: Test Fixup

#19501 perlhack: make language about 79-col lines laxer
  pod/perlhack.pod
Labels: documentation

#19548 Correct POD formatting error
  Porting/release_managers_guide.pod
Labels: documentation
