Repository Perl/perl5, pull requests merged in 2022-07, with the labels that each got.

#19854 Add builtin::is_tainted
  builtin.c
  ext/Opcode/Opcode.pm
  lib/B/Deparse.pm
  lib/B/Deparse.t
  lib/B/Op_private.pm
  lib/builtin.pm
  lib/builtin.t
  opcode.h
  opnames.h
  pp.c
  pp_proto.h
  regen/opcodes
  t/perf/opcount.t
Labels: hasConflicts

#19843 on freebsd replace the first part of archname with `uname -p`
  hints/freebsd.sh
Labels: distro-freebsd

#19969 Add Haarg to the Core Team
  Porting/core-team.json
  pod/perlgov.pod
Labels: Infrastructure

#19879 Adjust PSC with 2022 members
  Porting/vote_admin_guide.pod
Labels: Infrastructure
