Repository Perl/perl5, pull requests merged in 2022-08, with the labels that each got.

#20029 perlfunc - correct argument terminology for dbmopen
  pod/perlfunc.pod
Labels: documentation

#20064 win32.c: use _mkgmtime() instead of mktime() in stat()
  pod/perldelta.pod
  win32/win32.c
Labels: Win32

#20076 Add what-to-do when push after merge fails
  pod/perlgit.pod
Labels: Infrastructure

#20097 Fix g++ builds (/ locale.c: Fix trial_locales declaration)
  locale.c
Labels: type-locale

#19943 Implement OP_PADSV_STORE - combined sassign/padsv OP
  ext/B/t/b.t
  ext/B/t/optree_concise.t
  ext/B/t/optree_samples.t
  ext/B/t/optree_varinit.t
  ext/Opcode/Opcode.pm
  lib/B/Deparse.pm
  lib/B/Op_private.pm
  opcode.h
  opnames.h
  peep.c
  pp_hot.c
  pp_proto.h
  regen/op_private
  regen/opcodes
  t/perf/opcount.t
Labels: Ready-to-merge

#20111 win32: check if CCHOME is correctly set
  win32/GNUmakefile
  win32/Makefile
  win32/config_sh.PL
Labels: distro-mswin32

#20078 Langinfo.t: Handle systems without LC_ALL
  ext/I18N-Langinfo/t/Langinfo.t
Labels: type-locale

#20083 win32: Remove trailing backslash from `INST_TOP`
  win32/GNUmakefile
Labels: distro-mswin32

#20127 Use Windows system default locale
  locale.c
  t/run/locale.t
Labels: distro-mswin32

#20033 Handle intrin files on win32 with gcc
  .mailmap
  AUTHORS
  ext/Errno/Errno_pm.PL
Labels: distro-mswin32

#20154 [doc] Update File::stat synopsis
  lib/File/stat.pm
Labels: documentation
