Repository Perl/perl5, pull requests merged in 2022-09, with the labels that each got.

#20237 perlfilter.pod: Retain entry in customized database
  t/porting/customized.dat
  t/porting/customized.t
Labels: Infrastructure

#20216 Net-Ping: No longer need to TODO some tests when on FreeBSD
  dist/Net-Ping/t/010_pingecho.t
  dist/Net-Ping/t/450_service.t
  t/porting/customized.dat
Labels: distro-freebsd

#20320 Bisect runner errors 20220919
  Porting/bisect-runner.pl
Labels: Infrastructure

#19893 Update STMT_START..END guidance
  perl.h
  pod/perlhacktips.pod
Labels: documentation

#19810 RMG: Add step for deprecation/experimental resolution
  Porting/release_managers_guide.pod
Labels: documentation
