Repository Perl/perl5, pull requests merged in 2022-06, with the labels that each got.

#19703 perlapi: Document do_close
  doio.c
Labels: documentation

#19745 perlapi: Document my_failure_exit()
  embed.fnc
  perl.c
Labels: documentation

#19802 feature - document that use utf8 should probably be used for non-ascii delimiters
  lib/feature.pm
  regen/feature.pl
Labels: documentation

#18882 pp_unshift: av_store is often unnecessary
  pp.c
Labels: Ready-to-merge

#19834 minitest_prep conflict on building $(MINIPERL_EXE)
  Makefile.SH
Labels: miniperl

#19797 Fix building with clang-cl
  .mailmap
  AUTHORS
  win32/win32.h
Labels: distro-mswin32
