Repository Perl/perl5, pull requests merged in 2023-09, with the labels that each got.

#21435 perlop, perlsyn: make abstract more verbose/precise
  MANIFEST
  pod/perl.pod
  pod/perlop.pod
  pod/perlsyn.pod
  t/porting/known_pod_issues.dat
Labels: documentation

#21418 `Maintainers.pl`: use `strict`/`warnings` pragmas with `our` scoping
  Porting/Maintainers.pl
Labels: Infrastructure

#21409 `core-cpan-diff`: Make Options Display Consistently in Usage Output
  Porting/core-cpan-diff
Labels: Infrastructure

#21461 Update ParseXS entry to reflect actual $VERSION
  Porting/Maintainers.pl
Labels: Infrastructure

#21464 [doc] Fix 'comprised of'
  AUTHORS
  dist/Data-Dumper/Dumper.pm
  dist/base/lib/fields.pm
  pod/perl5180delta.pod
  pod/perl561delta.pod
  pod/perl56delta.pod
  pod/perldiag.pod
  pod/perlunicode.pod
  sv.c
  t/uni/lex_utf8.t
Labels: documentation

#21468 Enable thread-safe locales on openbsd
  hints/openbsd.sh
Labels: distro-openbsd

#21510 Avoid build-time warning
  ext/XS-Typemap/Typemap.pm
  ext/XS-Typemap/Typemap.xs
Labels: build-time-warnings
