Repository Perl/perl5, pull requests merged in 2023-03, with the labels that each got.

#20880 dist/Thread-Queue - add missing build artifacts
  MANIFEST
  Porting/exec-bit.txt
  dist/Thread-Queue/.gitignore
  dist/Thread-Queue/Changes
  dist/Thread-Queue/Makefile.PL
  dist/Thread-Queue/examples/callback.pl
  dist/Thread-Queue/examples/queue.pl
Labels: hasConflicts

#20895 tweak MANIFEST sort order, better description indentation
  MANIFEST
  Porting/manifest_lib.pl
Labels: type-build

#20979 [doc] update description of $^H and %^H in perlvar
  pod/perlvar.pod
Labels: documentation

#20780 Update `pop()` and `shift()` docs with examples
  pod/perlfunc.pod
Labels: documentation
