Repository Perl/perl5, pull requests merged in 2023-05, with the labels that each got.

#21063 Remove my_strftime8()
  embed.fnc
  embed.h
  ext/POSIX/POSIX.xs
  ext/POSIX/lib/POSIX.pm
  locale.c
  pod/perldelta.pod
  proto.h
Labels: Release Blocker

#21048 Still cleaning up Y2K residue
  pod/perlfunc.pod
Labels: documentation

#21035 perlwin32: Add link to MS Build Tools
  README.win32
Labels: distro-mswin32

#21046 Add missing ccflags on VMS to dist/Time-HiRes/Makefile.PL
  dist/Time-HiRes/Makefile.PL
Labels: distro-vms

#21128 dist/Storable - security advisory and changelog update
  dist/Storable/ChangeLog
  dist/Storable/Storable.pm
Labels: dist-Storable
