Repository Perl/perl5, pull requests merged in 2023-08, with the labels that each got.

#21021 perlrequick: Note {,n} added in 5.34
  pod/perlrequick.pod
Labels: documentation

#21306 Add `__CLASS__` keyword
  class.c
  embed.h
  ext/Opcode/Opcode.pm
  ext/Pod-Functions/t/Functions.t
  keywords.c
  keywords.h
  lib/B/Deparse-core.t
  op.c
  opcode.h
  opnames.h
  pod/perlclass.pod
  pod/perldiag.pod
  pod/perlfunc.pod
  pp_proto.h
  proto.h
  regen/embed_lib.pl
  regen/keywords.pl
  regen/opcodes
  t/class/class.t
  t/class/inherit.t
  t/class/phasers.t
  t/lib/croak/class
  t/op/coreamp.t
  t/op/coresubs.t
  toke.c
Labels: squash-before-merge

#21000 Add a step to the RMG about podcheck
  Porting/release_managers_guide.pod
Labels: Infrastructure

#21382 pod: eliminate references to `$a` and `$b` outside sort context
  pod/buildtoc
  pod/perlcall.pod
  pod/perldbmfilter.pod
  pod/perldiag.pod
  pod/perldsc.pod
  pod/perlebcdic.pod
  pod/perlembed.pod
  pod/perlfunc.pod
  pod/perlgit.pod
  pod/perlhacktips.pod
  pod/perlinterp.pod
  pod/perlintro.pod
  pod/perllocale.pod
  pod/perlop.pod
  pod/perlpodspec.pod
  pod/perlre.pod
  pod/perlrebackslash.pod
  pod/perlrecharclass.pod
  pod/perlref.pod
  pod/perlsyn.pod
  pod/perltie.pod
  pod/perluniintro.pod
Labels: documentation

#20631 Minor updates for release documentation
  Porting/how_to_write_a_perldelta.pod
  Porting/release_managers_guide.pod
Labels: Infrastructure

#21408 Smoke me/jkeenan/gh 21393 unused var
  pp_ctl.c
Labels: build-time-warnings, squash-before-merge
