Repository Perl/perl5, pull requests merged in 2023-10, with the labels that each got.

#21538 perl51200delta: fix typo (missing '.')
  pod/perl5120delta.pod
Labels: documentation

#21537 Get /o off of perlop.pod
  pod/perlop.pod
Labels: documentation

#20301 Adapt malloc.c to croak/warn now being defined under multiplicity #20286
  malloc.c
Labels: build-time-warnings

#21548 Fix various issues with the POSIX.xs typemap
  ext/POSIX/typemap
Labels: POSIX

#21557 Bisection: Document use of '--one-liner' switch
  Porting/bisect-runner.pl
  t/porting/known_pod_issues.dat
Labels: documentation, Infrastructure

#21566 don't clear IOK on @{"_<$file"} entries when a dbstate is freed
  lib/perl5db.t
  op.c
Labels: backport-5.36, backport-5.38

#21520 `File-Find`: Minor tests/docs improvements
  ext/File-Find/lib/File/Find.pm
  ext/File-Find/t/find.t
  ext/File-Find/t/taint.t
  t/porting/known_pod_issues.dat
Labels: ext-File-Find
