Repository Perl/perl5, pull requests merged in 2023-01, with the labels that each got.

#20657 testsuite.yaml - do a less shallow clone
  t/porting/update_authors.t
Labels: type-github-ci

#20621 Fix PerlEnv_putenv threaded compilation on Windows
  embed.fnc
  embed.h
  inline.h
  iperlsys.h
  proto.h
Labels: distro-mswin32

#20738 Update `unshift()` documentation to include examples and be more novice friendly
  pod/perlfunc.pod
Labels: documentation

#20752 [Pod] UNIVERSAL: Add lexical variables in Synopsis
  lib/UNIVERSAL.pm
Labels: documentation
