Repository Perl/perl5, pull requests merged in 2023-11, with the labels that each got.

#21601 Announce 5.42 removal of goto to jump into construct
  pod/perldiag.pod
  pod/perlfunc.pod
  pp_ctl.c
  t/op/goto.t
  t/porting/deprecation.t
Labels: documentation

#21633 Skip threaded locale test on OpenBSD and Dragonfly
  lib/locale_threads.t
Labels: distro-dragonfly, distro-openbsd

#21629 cpan/Getopt-Long - Update to version 2.57
  MANIFEST
  Makefile.SH
  Porting/Maintainers.pl
  cpan/Getopt-Long/lib/Getopt/Long.pm
  cpan/Getopt-Long/lib/Getopt/Long/Parser.pm
  cpan/Getopt-Long/t/gol-load1.t
  cpan/Getopt-Long/t/gol-load2.t
  cpan/Getopt-Long/t/gol-oo.t
  lib/.gitignore
  win32/GNUmakefile
  win32/Makefile
  write_buildcustomize.pl
Labels: squash-before-merge

#21638 Don't use POSIX 2008 locale on Dragonfly
  hints/dragonfly.sh
Labels: distro-dragonfly

#21643 Fix a compiler warning for 32-bit build in pp.c
  pp.c
Labels: build-time-warnings

#21659 Fix a compiler warning for 32-bit build in locale.c
  locale.c
Labels: build-time-warnings

#21591 perlport changes for windows
  pod/perlport.pod
Labels: documentation, Win32
