Repository Perl/perl5, pull requests merged in 2024-12, with the labels that each got.

#22807 sv_inline.h:Perl_new_sv: prevent unused parameter warnings
  sv_inline.h
Labels: build-time-warnings

#22808 refcounted_he_(new|fetch)_pvn: Don't roll-own code
  hv.c
Labels: squash-before-merge

#22859 Avoid uninitialized value warning
  utf8.c
Labels: build-time-warnings, squash-before-merge
