Repository Perl/perl5, pull requests merged in 2024-05, with the labels that each got.

#22184 Update location of further documentation
  dist/ExtUtils-ParseXS/lib/perlxs.pod
Labels: documentation

#22196 POSIX/t/wrappers.t: One-character typo
  ext/POSIX/t/wrappers.t
Labels: POSIX

#22191 Fcntl: add module documentation
  ext/Fcntl/Fcntl.pm
  t/porting/known_pod_issues.dat
Labels: documentation

#22200 perllocale: Update for 5.40 state of affairs
  pod/perllocale.pod
  t/porting/known_pod_issues.dat
Labels: documentation, type-locale

#22218 `perlbook.pod`: Fix few leftovers
  pod/perlbook.pod
Labels: documentation

#22203 perlfunc/stat: fix description of S_ENFMT and S_IFMT
  pod/perlfunc.pod
Labels: documentation

#22197 Core vs posix gh 16163 20240505
  ext/POSIX/lib/POSIX.pod
  ext/POSIX/t/usage.t
Labels: documentation, POSIX

#22220 perlfunc - Describe and provide examples of my/state/local/our effects within a statement
  pod/perlfunc.pod
Labels: documentation

#22254 perlfunc: clarify why use VERSION does not load pragma files
  pod/perlfunc.pod
Labels: documentation
