Repository Perl/perl5, pull requests merged in 2024-09, with the labels that each got.

#22227 Document the behaviour of int("NaN")
  pod/perlfunc.pod
Labels: documentation

#21396 S_bool_setlocale_2008_i, S_querylocale_2008_i: Add entry assertions
  locale.c
Labels: type-locale

#22573 dump.c: Handle op_aux items of newer UNOP_AUX op types in op_dump()
  dump.c
Labels: squash-before-merge

#22584 Devel::Peek: fix build warning
  ext/Devel-Peek/Peek.pm
  ext/Devel-Peek/Peek.xs
Labels: build-time-warnings

#22601 Storable: stop using bareword file handles
  dist/Storable/lib/Storable.pm
Labels: BBC

#21246 utf8_hop_forward: Don't go over edge of buffer
  inline.h
Labels: needsTest
