Repository Perl/perl5, pull requests merged in 2024-07, with the labels that each got.

#22368 pp_chdir: simplify control flow in fchdir case
  pp_sys.c
Labels: hasConflicts

#22381 write_buildcustomize.pl: Standardize indents at 4 spaces
  write_buildcustomize.pl
Labels: Infrastructure

#22387 Mark `__CLASS__` as experimental
  pod/perldiag.pod
  toke.c
Labels: class

#22388 wording improvement in gory parsing details
  pod/perlop.pod
Labels: documentation

#21349 Update Safe metadata
  dist/Safe/Makefile.PL
Labels: type-dist
