Repository Perl/perl5, pull requests merged in 2025-05, with the labels that each got.

#23235 cpan/experimental - Update to version 0.035
  Porting/Maintainers.pl
  cpan/experimental/lib/experimental.pm
  cpan/experimental/lib/stable.pm
Labels: Release Blocker

#23250 perlop/perlvar: Mention diamond operators
  pod/perlop.pod
  pod/perlvar.pod
Labels: documentation

#23252 perlvar: Add link to remaining legal $# use
  pod/perlvar.pod
Labels: documentation

#23260 perlfunc: Improve each, keys, values pod
  pod/perlfunc.pod
Labels: documentation

#23245 podcheck.t: Minimize exceptions db entries
  t/porting/known_pod_issues.dat
  t/porting/podcheck.t
Labels: Infrastructure

#23258 perlnumber: Leading 0 in string doesn't imply octal
  pod/perlnumber.pod
Labels: documentation

#23269 perlop: Update extra paired delims to Unicode 16
  pod/perlop.pod
Labels: documentation

#23270 Note regex_sets is a synonym
  pod/perlrecharclass.pod
Labels: documentation

#23263 perlfunc: Remove self-referential links
  pod/perlfunc.pod
Labels: documentation

#23216 better suggestions for builtin::trim equivalence (Resolves #23212)
  lib/builtin.pm
  t/porting/known_pod_issues.dat
Labels: documentation

#23247 perlop: Remove extra parens in verbatim examples
  pod/perlop.pod
Labels: documentation

#23249 perlref: Add example of lhs postfix deref
  pod/perlref.pod
Labels: documentation

#23273 run/locale.t: Skip tests if no appropriate locale
  t/run/locale.t
Labels: distro-openbsd, type-locale

#23283 perlre: fix incorrect pod escape
  pod/perlre.pod
Labels: documentation

#23007 Unicode:UCD Clarify pod for num()
  charclass_invlists.inc
  lib/Unicode/UCD.pm
  lib/unicore/uni_keywords.pl
  regcharclass.h
  regexp_constants.h
  uni_keywords.h
Labels: documentation, type-Unicode

#23294 perlintro: Add discussion of sigils
  pod/perlintro.pod
Labels: documentation

#23328 perlintern: Note that prefer inline function to PL_Sv
  intrpvar.h
Labels: documentation
