Repository Perl/perl5, pull requests merged in 2025-07, with the labels that each got.

#23357 perlrun: add caution that the -C flag does not validate nor produce UTF-8
  pod/perlrun.pod
Labels: documentation

#22455 perlipc.pod: correct the safe signals bypass suggestion
  pod/perlipc.pod
Labels: documentation

#23437 'try' and 'catch' are no longer experimental
  pod/perlfunc.pod
Labels: documentation

#22291 perlintern: Document sv_dup(_inc)?
  embed.fnc
  sv.c
Labels: documentation

#23411 perlop: Clarify empty pattern section not valid for qr//
  pod/perlop.pod
Labels: documentation

#23234 sv.c: make PUSH_EXTEND_MORTAL__SV_C an inline function
  sv.c
Labels: hasConflicts

#23499 Reapply "op.c: re-enable coderef-in-stash optimization"
  class.c
  op.c
  t/op/sub.t
Labels: optimization
