Repository Perl/perl5, pull requests merged in 2025-04, with the labels that each got.

#23166 PathTools: check Config values early before chdir
  dist/PathTools/Cwd.pm
  dist/PathTools/lib/File/Spec.pm
  dist/PathTools/lib/File/Spec/AmigaOS.pm
  dist/PathTools/lib/File/Spec/Cygwin.pm
  dist/PathTools/lib/File/Spec/Epoc.pm
  dist/PathTools/lib/File/Spec/Functions.pm
  dist/PathTools/lib/File/Spec/Mac.pm
  dist/PathTools/lib/File/Spec/OS2.pm
  dist/PathTools/lib/File/Spec/Unix.pm
  dist/PathTools/lib/File/Spec/VMS.pm
  dist/PathTools/lib/File/Spec/Win32.pm
  dist/PathTools/t/cwd_enoent.t
Labels: dist-PathTools

#23188 Time::HiRes: fix manpage links
  dist/Time-HiRes/HiRes.pm
Labels: documentation

#23184 POSIX: fix man page links
  ext/POSIX/lib/POSIX.pod
Labels: documentation

#23165 Dumper.xs: use new SvVSTRING API
  dist/Data-Dumper/Dumper.xs
Labels: dist-Data-Dumper

#23191 Improve appearance of the descriptions of `-M`/`-m` switches in perlrun.pod
  pod/perlrun.pod
Labels: documentation

#23167 dist-modules: fix selection of a threaded perl
  .github/workflows/testsuite.yml
Labels: Infrastructure

#22658 perlop: fix and normalize indentation and alignment
  pod/perldelta.pod
  pod/perlop.pod
Labels: documentation
